# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709c036d711bf6436ed63aad25538c0f2d8d0a747f3604e893d6ea288ab4827873570bc7bd6cee7cb8573e77935033045492efbfd51ae164e14710f14f1dcc6a

test:
  secret_key_base: d5f96f039a400db46e99fc68ff3c4815938ecce75633be59dc5952522e1e7715497c93672175a3d6f933daa89052246385d909f544c4c3d9affe5b3a658ba566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
